# Generated by Django 5.2.8 on 2025-11-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neon', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeonModel',
            new_name='Neon',
        ),
    ]
